#!/usr/bin/env bun
/**
 * Fetches the Google Fonts metadata and generates a compact TypeScript catalog.
 * Run: bun scripts/generate-font-catalog.ts
 *
 * All Google Fonts are licensed under either:
 *   - SIL Open Font License 1.1 (OFL) — allows commercial use, bundling, modification
 *   - Apache License 2.0 — allows commercial use, bundling, modification
 * Both licenses permit end-users to create commercial works with the fonts.
 */

const METADATA_URL = 'https://fonts.google.com/metadata/fonts'

interface GoogleFontMeta {
  family: string
  displayName?: string
  category: string
  axes: Array<{ tag: string; min: number; max: number; defaultValue: number }>
  fonts: Record<string, { thickness: number; slant: number; width: number }>
  subsets: string[]
  designers: string[]
  lastModified: string
  popularity: number
  trending: number
  license: string // 'ofl' | 'apache2' | 'ufl'
  classifications?: string[]
}

interface GoogleMetaResponse {
  familyMetadataList: GoogleFontMeta[]
  axisRegistry: Array<{
    tag: string
    displayName: string
    min: number
    max: number
    defaultValue: number
    precision: number
    description: string
  }>
}

// Compact output format
interface CatalogFont {
  f: string // family
  c: number // category index: 0=sans-serif 1=serif 2=display 3=handwriting 4=monospace
  w: number[] // available weights (for static fonts)
  a?: [string, number, number][] // variable axes: [tag, min, max]
  p: number // popularity rank (lower = more popular)
  l: number // license: 0=ofl 1=apache2 2=ufl
  s?: number // 1 if supports latin only, omitted if broad
  i?: 1 // 1 if italic variant exists
}

const CATEGORY_MAP: Record<string, number> = {
  'sans-serif': 0,
  'Sans Serif': 0,
  serif: 1,
  Serif: 1,
  display: 2,
  Display: 2,
  handwriting: 3,
  Handwriting: 3,
  monospace: 4,
  Monospace: 4,
}

const LICENSE_MAP: Record<string, number> = {
  ofl: 0,
  apache2: 1,
  ufl: 2,
}

async function main() {
  console.log('Fetching Google Fonts metadata...')
  const resp = await fetch(METADATA_URL)
  const text = await resp.text()
  // Google prefixes the response with ")]}'" for XSSI protection
  const json = JSON.parse(text.replace(/^\)\]\}'\n/, '')) as GoogleMetaResponse

  const fonts = json.familyMetadataList

  console.log(`Found ${fonts.length} font families`)

  // Sort by popularity (lower number = more popular)
  fonts.sort((a, b) => a.popularity - b.popularity)

  const catalog: CatalogFont[] = []

  for (let i = 0; i < fonts.length; i++) {
    const font = fonts[i]!
    const category = CATEGORY_MAP[font.category] ?? 0
    const license = LICENSE_MAP[font.license] ?? 0

    // Extract available weights from font style keys (e.g. "100", "200i", "400", "700italic")
    const weights = new Set<number>()
    let hasItalic = false
    for (const style of Object.keys(font.fonts)) {
      const numMatch = style.match(/^(\d+)/)
      if (numMatch) {
        weights.add(parseInt(numMatch[1]!, 10))
      }
      if (style.includes('i')) {
        hasItalic = true
      }
    }
    // Ensure at least weight 400
    if (weights.size === 0) weights.add(400)

    // Variable axes
    const axes: [string, number, number][] | undefined =
      font.axes.length > 0 ? font.axes.map((a) => [a.tag, a.min, a.max]) : undefined

    // If it has a wght axis, we don't need to list individual weights
    const hasWeightAxis = axes?.some(([tag]) => tag === 'wght')

    const entry: CatalogFont = {
      f: font.family,
      c: category,
      w: hasWeightAxis ? [] : Array.from(weights).sort((a, b) => a - b),
      p: i,
      l: license,
    }

    if (axes) entry.a = axes
    if (hasItalic) entry.i = 1

    // Check if only latin subset
    if (font.subsets.length === 1 && font.subsets[0] === 'latin') {
      entry.s = 1
    }

    catalog.push(entry)
  }

  // Generate TypeScript file
  const output = `// Auto-generated by scripts/generate-font-catalog.ts — do not edit manually
// Source: Google Fonts (https://fonts.google.com)
// All fonts are licensed under OFL 1.1 or Apache 2.0
// Generated: ${new Date().toISOString().split('T')[0]}
// Total: ${catalog.length} font families

/** Category indices: 0=sans-serif 1=serif 2=display 3=handwriting 4=monospace */
export const CATEGORIES = ['sans-serif', 'serif', 'display', 'handwriting', 'monospace'] as const
export type FontCategory = (typeof CATEGORIES)[number]

/** License indices: 0=OFL 1.1  1=Apache 2.0  2=Ubuntu Font License */
export const LICENSES = ['SIL Open Font License 1.1', 'Apache License 2.0', 'Ubuntu Font License'] as const

export interface CatalogFont {
  /** Font family name */
  f: string
  /** Category index */
  c: number
  /** Available weights (empty if variable with wght axis) */
  w: number[]
  /** Variable axes: [tag, min, max][] */
  a?: [string, number, number][]
  /** Popularity rank (0 = most popular) */
  p: number
  /** License index */
  l: number
  /** 1 if latin-only subset */
  s?: number
  /** 1 if italic variant exists */
  i?: 1
}

export const FONT_CATALOG: CatalogFont[] = ${JSON.stringify(catalog)}
`

  const outPath = new URL('../src/fonts/catalog.ts', import.meta.url).pathname
  await Bun.write(outPath, output)
  console.log(`Wrote ${catalog.length} fonts to ${outPath}`)

  // Print stats
  const variable = catalog.filter((f) => f.a && f.a.length > 0).length
  const byCategory = [0, 0, 0, 0, 0]
  for (const f of catalog) byCategory[f.c]!++
  console.log(`  Variable fonts: ${variable}`)
  console.log(`  Sans-serif: ${byCategory[0]}`)
  console.log(`  Serif: ${byCategory[1]}`)
  console.log(`  Display: ${byCategory[2]}`)
  console.log(`  Handwriting: ${byCategory[3]}`)
  console.log(`  Monospace: ${byCategory[4]}`)
}

main().catch(console.error)
